# 正規化
+ バッチ正規化
+ レイヤー正規化
+ インスタンス正規化
+ グループ正規化

### いつもの設定

In [1]:
from type_hint import *
from import_str import importstr
from log_conf import logging
log = logging.getLogger('nb')

# log.setLevel(logging.WARN)
log.setLevel(logging.INFO)
log.setLevel(logging.DEBUG)

# running everything app
def run(app, *argv):
    argv = list(argv)
    log.info('Running: {}({!r}).main()'.format(app, argv))
    print("*app.rsplit('.', 1) : ", *app.rsplit('.', 1))

    app_cls = importstr(*app.rsplit('.', 1)) # __import__を実行
    app_cls(argv).main()

    log.info("Finished: {}.({!r}).main()".format(app, argv))

module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/..
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/..
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/..


### Batch Normalization

BatchNorm1d (N, C) or (N, C, L)

In [2]:
run('Normalization.batch_norm.BatchNorm1dApp')

2023-06-22 15:52:05,155 INFO     pid:4628 nb:013:run Running: Normalization.batch_norm.BatchNorm1dApp([]).main()


*app.rsplit('.', 1) :  Normalization.batch_norm BatchNorm1dApp
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/Normalization/..


2023-06-22 15:52:07,665 INFO     pid:4628 Normalization.batch_norm:044:main Starting BatchNorm1dApp, Namespace()
2023-06-22 15:52:07,670 INFO     pid:4628 nb:019:run Finished: Normalization.batch_norm.BatchNorm1dApp.([]).main()


(N, C) input [L=1]--------------------------------------
input_2dim.shape torch.Size([2, 3])
input_2dim: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
gamma.shape torch.Size([3])
gamma: 
 Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
beta.shape torch.Size([3])
beta: 
 Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
output_2dim.shape torch.Size([2, 3])
output_2dim: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]], grad_fn=<NativeBatchNormBackward0>)
(N, C, L) input [Main]--------------------------------------
input_3dim.shape torch.Size([2, 3, 4])
input_3dim: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
gamma.shape torch.Size([3])
gamma: 
 Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
beta.shape torch.Size([3])
beta: 
 Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
output_3dim.shape torch.Size([2, 3, 4])

BatchNorm2d (N, C, H, W)

In [3]:
run('Normalization.batch_norm.BatchNorm2dApp')

2023-06-22 15:52:07,681 INFO     pid:4628 nb:013:run Running: Normalization.batch_norm.BatchNorm2dApp([]).main()
2023-06-22 15:52:07,688 INFO     pid:4628 Normalization.batch_norm:108:main Starting BatchNorm2dApp, Namespace()
2023-06-22 15:52:07,698 INFO     pid:4628 nb:019:run Finished: Normalization.batch_norm.BatchNorm2dApp.([]).main()


*app.rsplit('.', 1) :  Normalization.batch_norm BatchNorm2dApp
(N, C, H, W) input [Main]--------------------------------------
input_4dim.shape torch.Size([2, 3, 4, 4])
input_4dim: 
 tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
gamma.shape torch.Size([3])
gamma: 
 Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
beta.shape torch.Size([3])
bet

BatchNorm3d (N, C, D, H, W)

In [4]:
run('Normalization.batch_norm.BatchNorm3dApp')

2023-06-22 15:52:07,732 INFO     pid:4628 nb:013:run Running: Normalization.batch_norm.BatchNorm3dApp([]).main()
2023-06-22 15:52:07,753 INFO     pid:4628 Normalization.batch_norm:153:main Starting BatchNorm3dApp, Namespace()
2023-06-22 15:52:07,778 INFO     pid:4628 nb:019:run Finished: Normalization.batch_norm.BatchNorm3dApp.([]).main()


*app.rsplit('.', 1) :  Normalization.batch_norm BatchNorm3dApp
(N, C, D, H, W) input [Main]--------------------------------------
input_5dim.shape torch.Size([2, 3, 4, 4, 4])
input_5dim: 
 tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1.

### Layer Normalization

LayerNorm (N, C, H, W), (N, C, D), etc = (N, *)

In [5]:
run('Normalization.layer_norm.LayerNormApp')

2023-06-22 15:52:07,804 INFO     pid:4628 nb:013:run Running: Normalization.layer_norm.LayerNormApp([]).main()


2023-06-22 15:52:07,818 INFO     pid:4628 Normalization.layer_norm:044:main Starting LayerNormApp, Namespace()
2023-06-22 15:52:07,824 INFO     pid:4628 nb:019:run Finished: Normalization.layer_norm.LayerNormApp.([]).main()


*app.rsplit('.', 1) :  Normalization.layer_norm LayerNormApp
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/Normalization/..
v_t.shape torch.Size([2, 3])
v_t: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
v_t.mean((-2,-1)) tensor(3.5000)
input.shape torch.Size([2, 3, 2, 2])
input: 
 tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
output.shape torch.Size([2, 3])
output: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
gamma.shape torch.Size([2, 2])
gamma: 
 Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
beta.shape torch.Size([2, 2])
beta: 
 Parameter containing:
tensor([[0., 0.],
        [0., 0.]], requires_grad=True)
output_layer_nrom.shape torch.Size([2, 3, 2, 2])
output_layer_nrom: 
 tensor([[[[0., 0.],
          [0., 0.]],

        

### Instance Normalization

InstanceNorm1d (N, C, L) or (C, L)

In [6]:
run('Normalization.instance_norm.InstanceNorm1dApp')

2023-06-22 15:52:07,841 INFO     pid:4628 nb:013:run Running: Normalization.instance_norm.InstanceNorm1dApp([]).main()
2023-06-22 15:52:07,846 INFO     pid:4628 Normalization.instance_norm:044:main Starting InstanceNorm1dApp, Namespace()
2023-06-22 15:52:07,854 INFO     pid:4628 nb:019:run Finished: Normalization.instance_norm.InstanceNorm1dApp.([]).main()


*app.rsplit('.', 1) :  Normalization.instance_norm InstanceNorm1dApp
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/Normalization/..
(C, L) input --------------------------------------
input_2dim.shape torch.Size([3, 4])
input_2dim: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
gamma.shape torch.Size([3])
gamma: 
 Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
beta.shape torch.Size([3])
beta: 
 Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
output_2dim.shape torch.Size([3, 4])
output_2dim: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], grad_fn=<SqueezeBackward1>)
(N, C, L) input [Main]--------------------------------------
input_3dim.shape torch.Size([2, 3, 4])
input_3dim: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
output_3dim.shape torch.Size([2,

InstanceNorm2d (N, C, H, W) or (C, H, W)

In [7]:
run('Normalization.instance_norm.InstanceNorm2dApp')

2023-06-22 15:52:07,870 INFO     pid:4628 nb:013:run Running: Normalization.instance_norm.InstanceNorm2dApp([]).main()
2023-06-22 15:52:07,874 INFO     pid:4628 Normalization.instance_norm:114:main Starting InstanceNorm2dApp, Namespace()
2023-06-22 15:52:07,884 INFO     pid:4628 nb:019:run Finished: Normalization.instance_norm.InstanceNorm2dApp.([]).main()


*app.rsplit('.', 1) :  Normalization.instance_norm InstanceNorm2dApp
(C, H, W) input --------------------------------------
input_3dim.shape torch.Size([3, 4, 4])
input_3dim: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
gamma.shape torch.Size([3])
gamma: 
 Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
beta.shape torch.Size([3])
beta: 
 Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
output_3dim.shape torch.Size([3, 4, 4])
output_3dim: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0.

InstanceNorm3d (N, C, D, H, W) or (C, D, H, W)

In [8]:
run('Normalization.instance_norm.InstanceNorm3dApp')

2023-06-22 15:52:07,914 INFO     pid:4628 nb:013:run Running: Normalization.instance_norm.InstanceNorm3dApp([]).main()
2023-06-22 15:52:07,930 INFO     pid:4628 Normalization.instance_norm:182:main Starting InstanceNorm3dApp, Namespace()


*app.rsplit('.', 1) :  Normalization.instance_norm InstanceNorm3dApp
(C, D, H, W) input [Main]----------------------------------
input_4dim.shape torch.Size([3, 4, 4, 4])
input_4dim: 
 tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 

2023-06-22 15:52:07,962 INFO     pid:4628 nb:019:run Finished: Normalization.instance_norm.InstanceNorm3dApp.([]).main()


output_5dim.shape torch.Size([2, 3, 4, 4, 4])
output_5dim: 
 tensor([[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 

### GroupNorm

GroupNorm (N, C, *)

In [9]:
run('Normalization.group_norm.GroupNormApp')

2023-06-22 15:52:08,040 INFO     pid:4628 nb:013:run Running: Normalization.group_norm.GroupNormApp([]).main()
2023-06-22 15:52:08,052 INFO     pid:4628 Normalization.group_norm:044:main Starting GroupNormApp, Namespace()


*app.rsplit('.', 1) :  Normalization.group_norm GroupNormApp
module_parent_dir /Users/inoueshinichi/Desktop/MyGithub/Wiki_AI/Normalization/..
(N, C, H, W) input ------------------------------------
input_4dim.shape torch.Size([2, 9, 2, 2])
input_4dim: 
 

2023-06-22 15:52:08,138 INFO     pid:4628 nb:019:run Finished: Normalization.group_norm.GroupNormApp.([]).main()


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
gamma.shape torch.Size([9])
gamma: 
 Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
beta.shape torch.Size([9])
beta: 
 Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=T